/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InstallationsIdRouteImport } from './routes/installations.$id'
import { Route as InstallationsNewRouteImport } from './routes/installations.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsIdRoute = InstallationsIdRouteImport.update({
  id: '/installations/$id',
  path: '/installations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsNewRoute = InstallationsNewRouteImport.update({
  id: '/installations/new',
  path: '/installations/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installations/$id': typeof InstallationsIdRoute
  '/installations/new': typeof InstallationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installations/$id': typeof InstallationsIdRoute
  '/installations/new': typeof InstallationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installations/$id': typeof InstallationsIdRoute
  '/installations/new': typeof InstallationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/installations/$id' | '/installations/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/installations/$id' | '/installations/new'
  id: '__root__' | '/' | '/auth' | '/installations/$id' | '/installations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InstallationsIdRoute: typeof InstallationsIdRoute
  InstallationsNewRoute: typeof InstallationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/$id': {
      id: '/installations/$id'
      path: '/installations/$id'
      fullPath: '/installations/$id'
      preLoaderRoute: typeof InstallationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/new': {
      id: '/installations/new'
      path: '/installations/new'
      fullPath: '/installations/new'
      preLoaderRoute: typeof InstallationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InstallationsIdRoute: InstallationsIdRoute,
  InstallationsNewRoute: InstallationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
