-- Price catalog for the final deviz
CREATE TABLE public.deviz_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL CHECK (category IN ('manopera','materiale')),
  item_no integer NOT NULL,
  name_ro text NOT NULL,
  um text,
  unit_price_eur numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (category, item_no)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.deviz_items TO authenticated;
GRANT ALL ON public.deviz_items TO service_role;
ALTER TABLE public.deviz_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog readable by authenticated" ON public.deviz_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "catalog editable by authenticated" ON public.deviz_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER deviz_items_updated BEFORE UPDATE ON public.deviz_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Per-installation deviz lines
CREATE TABLE public.deviz_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  installation_id uuid NOT NULL REFERENCES public.installations(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.deviz_items(id) ON DELETE RESTRICT,
  quantity numeric NOT NULL DEFAULT 0,
  auto_suggested boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (installation_id, item_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.deviz_lines TO authenticated;
GRANT ALL ON public.deviz_lines TO service_role;
ALTER TABLE public.deviz_lines ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own deviz lines" ON public.deviz_lines FOR ALL TO authenticated
  USING (public.owns_installation(installation_id)) WITH CHECK (public.owns_installation(installation_id));
CREATE TRIGGER deviz_lines_updated BEFORE UPDATE ON public.deviz_lines FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Extra fields needed by the acceptance report
ALTER TABLE public.fiber_routes ADD COLUMN segments jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE public.fiber_routes ADD COLUMN from_point text;
ALTER TABLE public.fiber_routes ADD COLUMN to_point text;
ALTER TABLE public.splice_closures ADD COLUMN code text;

INSERT INTO public.deviz_items (category,item_no,name_ro,um,unit_price_eur,sort_order) VALUES
('manopera',1,'Instalare microfibra in microtub prin suflare inclusiv suflarea rezervei de cablu in camin','km',323.0,0),
('manopera',2,'Instalare microfibra in microtub manual','km',420.0,1),
('manopera',3,'Intregirea traseului tubetelor in vederea operatirei de instalare a microfibrei. Conectorizare tubete 8-10 mm','buc',0.8,2),
('manopera',4,'Legarea rezervei cu fasete, fixarea pe peretele CT, protejarea microfibrei in CT, etichetarea, obturarea microtubului','buc',2.57,3),
('manopera',5,'Instalare tubeta de la iesirea din conducta de racord pana la jonctiune sau cutie, cu rol de protectie mecanica a microfibrei, daca este cazul','km',297.5,4),
('manopera',6,'Paftalat tubeta pe perete','km',246.085,5),
('manopera',7,'Sudura fibra optica','buc',4.0,6),
('manopera',8,'Inchidere/deschidere cutie de jonctiune/ODF - in cazul in care in cutie se executa mai putin de 5 lipituri','luc',11.9,7),
('manopera',9,'Masuratori OTDR','buc',5.95,8),
('manopera',10,'Pozat FO ADSS pe fatade de cladiri','km',430.0,9),
('manopera',11,'Instalare FO ADSS 2, 4, 8 sau 12 fire pe stalpi','km',380.0,10),
('manopera',12,'Instalare FO ADSS 24, 48 sau 96 fire pe stalpi','km',380.0,11),
('manopera',13,'Instalare FO ADSS 144 fire pe stalpi','km',380.0,12),
('manopera',14,'Instalare cablu la inaltime folosind inele de cablu','km',594.0,13),
('manopera',15,'Instalare cablu comunicatii prin pat de cablu','km',480.0,14),
('manopera',16,'Instalare cablu in monotub de protectie in vederea inglobarii in sape , tencuieli si plansee.','m',297.0,15),
('manopera',17,'Executie sant pentru instalare tevi in pamant - sapare, tasat, folie, acoperire si un tub','m3',8.3333,16),
('manopera',18,'Executie sant pentru instalare cablu FO "Direct Burried" - sapare, tasat, folie, acoperire','km',9000.0,17),
('manopera',19,'Instalare cablu sau monotub in sant existent - in plus fata de primul tub; ex: al 2-lea, etc.','km',264.0,18),
('manopera',20,'Instalare pat de cablu (plastic)','km',500.0,19),
('manopera',21,'Instalare microtub in monotub existent','km',297.5,20),
('manopera',22,'Instalare cablu FO in monotub sau canalizatie existenta','Km',323.0,21),
('manopera',23,'Protejare si aranjare cabluri coaxiale in camin de tragere','luc',41.0,22),
('manopera',24,'Instalat camereta vizitabila cu capac pietonal','luc',246.0,23),
('manopera',25,'Aducere gura vizitare camereta la cota','pcs',24.0,24),
('manopera',26,'Instalare dulap tehnic  stradal pt telecomunicatii','buc',304.0,25),
('manopera',27,'Inlocuire dulap tehnic stradal pt telecomunicatii','buc',46.0,26),
('manopera',28,'Montare cutie de jonctiune pe stalp','buc',15.0,27),
('manopera',29,'Montare cutie de jonctiune pe fatade/exterior','buc',15.0,28),
('manopera',30,'Montare cutie de jonctiune in interior','buc',10.0,29),
('manopera',31,'Demontare cablu comunicatii de pe fatade cladiri','km',200.0,30),
('manopera',32,'Demontare cablu comunicatii de pe stalpi','km',120.0,31),
('manopera',33,'Demontare cablu comunicatii din canalizatii sau tubulaturi','km',220.0,32),
('manopera',34,'Strapungere beton armat prin carotare','cm',1.62,33),
('manopera',35,'Strapungere beton armat prin gaurire cu burghiul','cm',3.23,34),
('manopera',36,'Strapungere in camereta de tragere','pcs',4.51,35),
('manopera',37,'Spargere beton la fundatie drum','m3',14.45,36),
('manopera',38,'Spargere beton la imbracaminte carosabila','m3',18.44,37),
('manopera',39,'Decapare imbrac. asfaltica cu strat pana la 3 cm','m2',0,38),
('manopera',40,'Taiere asfalt/beton cu masina disc diamantat','ml',2.55,39),
('manopera',41,'Compactarea cu mai a umpluturii','m3',0,40),
('manopera',42,'Refacere pavaje si asfaltare strazi (include materiale, transport si manopera)','m2',35.0,41),
('manopera',43,'Refacere pavaje din pavele (include materiale, transport, manopera)','m2',35.0,42),
('manopera',44,'Refacere spatiu verde','m2',15.0,43),
('manopera',45,'Forare orizontala cai ferate si groapa de lansare','m',43.49,44),
('manopera',46,'Forare orizontala drumuri si groapa de lansare','m',35.0,45),
('manopera',47,'Forare orizontala pentru subtraversare rauri cu lungimi mai mici de 100 ml','m',40.0,46),
('manopera',48,'Forare orizontala pentru subtraversare rauri cu lungimi mai mari de 100 ml','m',45.0,47),
('manopera',49,'Subtraversare pe sub conducte sau cabluri','pcs',25.0,48),
('manopera',50,'Semnalizare rutiera','pcs',10.0,49),
('manopera',51,'Dirijare circulatie rutiera','hour',6.0,50),
('manopera',52,'Instalare markeri electronici','pcs',15.0,51),
('manopera',53,'Modificare retea 0,4 kV clasic cu torsadat','m',2.0,52),
('manopera',54,'Obtinere pauze de tensiune','km',75.0,53),
('manopera',55,'Diagnosticare tronson FO defect','buc',60.0,54),
('manopera',56,'Etichetare cablu comunicatii in camerete (process de mentenanta)','buc',0.4474,55),
('manopera',57,'Etichetare cablu comunicatii aerian (process de mentenanta)','buc',0.5593,56),
('manopera',58,'Instalare cablu comunicatii fig8 (autopurtat) pe stalpi tip QR','km',396.0,57),
('manopera',59,'Instalare cablu comunicatii fig8 (autopurtat) pe stalpi tip F11','km',345.0,58),
('manopera',60,'Conectorizare cablu coaxial (QR, F11) in camereta','buc',1.4124,59),
('manopera',61,'Conectorizare cablu coaxial (QR, F11) pe stalpi/fatade cladiri','buc',1.0593,60),
('manopera',62,'Pozat cablu coaxial F11 pe fatade de cladiri','km',420.0,61),
('manopera',63,'Pozat cablu coaxial QR 540 pe fatade de cladiri','km',429.0,62),
('manopera',64,'Pozat cablu coaxial F11 pe fatade de cladiri la inaltime','km',429.0,63),
('manopera',65,'Pozat cablu coaxial QR 540 pe fatade de cladiri la inaltime','km',495.0,64),
('manopera',66,'Pozat cablu electric pe peretii cameretei sau pe fatade de cladiri','km',363.0,65),
('manopera',67,'Instalare cablu coaxial in canalizatie, in tub de 63mm, manual','km',420.0,66),
('manopera',68,'Instalat 1 x cablu coaxial QR 540 in tub','km',396.0,67),
('manopera',69,'Instalat 2 x cablu coaxial QR 540 in tub','km',478.5,68),
('manopera',70,'Instalat 3 x cablu coaxial QR 540 in tub','km',528.0,69),
('manopera',71,'Realizare retea de distributie bloc coloana P+4','luc',198.0,70),
('manopera',72,'Realizare retea de distributie bloc coloana P+6','luc',247.5,71),
('manopera',73,'Realizare retea de distributie bloc coloana P+8','luc',297.0,72),
('manopera',74,'Relocare cutie de distributie bloc','buc',23.0,73),
('manopera',75,'Montare/demontare cutie distributie','buc',3.5,74),
('manopera',76,'Montare sursa de alimentare pe stalp','luc',19.0,75),
('manopera',77,'Montare sursa de alimentare pe fatade','luc',23.0,76),
('manopera',78,'Montare UPS +baterii','luc',30.0,77),
('manopera',79,'Montare baterii','luc',15.0,78),
('manopera',80,'Executie bransament electric+BMP','luc',47.0,79),
('manopera',81,'Bransament electric interior','luc',20.0,80),
('manopera',82,'Revizie bransament electric','luc',7.0,81),
('manopera',83,'Bransament electric exterior pe stalp','luc',58.0,82),
('manopera',84,'Montare amplificator pe stalp sau strand (montare amplificator, conectorizare, mansonare)','buc',15.0,83),
('manopera',85,'Montare amplificator in camereta sau fatade (montare amplificator, conectorizare, mansonare)','buc',15.0,84),
('manopera',86,'Montare  nod optic pe stalp sau strand(include conectorizare, mansonare)','buc',15.0,85),
('manopera',87,'Montare  nod optic pe fatade/interior (include conectorizare, mansonare)','buc',15.0,86),
('manopera',88,'Reglare completa amplificator distributie','luc',10.0,87),
('manopera',89,'Reglare completa amplificator linie','luc',10.0,88),
('manopera',90,'Reglare completa nod optic','luc',10.0,89),
('manopera',91,'Montare pasive pe stalpi, fatade sau strand (include conectorizare, mansonare)','buc',5.0,90),
('manopera',92,'Montare elemente passive in camereta, interior','buc',4.0,91),
('manopera',93,'Inlocuire pasive din 2 in 4(inclusiv reconectorizare, mansonare)','buc',5.0,92),
('manopera',94,'Inlocuire pasive din 4 in 8(inclusiv reconectorizare, mansonare)','buc',6.0,93),
('manopera',95,'Demontare/Remontare protectie coloana securizata','buc',6.0,94),
('manopera',96,'Inlocuire cablu coax abonat','km',380.0,95),
('manopera',97,'Inlocuire amplificator','buc',15.0,96),
('manopera',98,'Clean-up lock-box','buc',50.0,97),
('manopera',99,'Inlocuire incuietoare cutie distributie','buc',6.0,98),
('manopera',100,'Mutare abonati de pe retea veche pe retea noua la case','buc',6.0,99),
('manopera',101,'Culegere date din teren Nr case + amplasare stalpi(pt harta)( walkout and as built network)','HP',6.88,100),
('manopera',102,'Proiectare retea HFC (include documentatie) - include culegere date din teren','HP',4.0,101),
('manopera',103,'Instalare stalp de lemn impregnat 8m, in teren normal','buc',40.0,102),
('manopera',104,'Instalare stalp material metalic','buc',100.0,103),
('manopera',105,'Instalare stalp material compozit','buc',100.0,104),
('manopera',106,'Instalare stalp din beton armat, 12m','buc',150.0,105),
('manopera',107,'Schimbare stalp LEA  0,4 kV(manopera)','pcs',0,106),
('manopera',108,'Schimbare stalp LEA  MT(manopera)','pcs',0,107),
('manopera',109,'Instalare strand pe stalpi (coliere de sustinere , bride , intindere)','km',35.0,108),
('manopera',110,'Demontare si recuperare CPE de la client','buc',5.0,109),
('manopera',111,'Instalare echipament CPE pus la dispozitie de Beneficiar cu acceptanta functionare de la client','buc',25.0,110),
('manopera',112,'Instalare echipament CPE pus la dispozitie de Beneficiar cu acceptanta functionare de la client in cazul swap-ului comercial cu recuperarea echipamentului inlocuit (vezi procesul de dezinstalare/recuperare)','buc',25.0,111),
('manopera',113,'Survey fibra optica/WiFi din birou (fara contactarea clientului)','luc',62.5,112),
('manopera',114,'Survey fibra optica - estimare traseu de la ultima CJ pana la clientul final cu inscriere traseu pe harta','luc',60.0,113),
('manopera',115,'Survey fibra optica si M2/kmz pentru identificare trasee infrastructura FO','luc',75.0,114),
('manopera',116,'Taxa de urgenta pentru executia de lucrari de instalare','luc',75.0,115),
('manopera',117,'Taxa de deplasare - "short range"','luc',50.0,116),
('manopera',118,'Taxa de deplasare - "long distance" / distante peste 50 Km','Km',50.0,117),
('manopera',119,'Evacuare apa camerete','Ora',2.68,118),
('manopera',120,'Update in bazele de date  (Optix, Mapinfo)','buc',35.0,119),
('manopera',121,'Instalare Media Converter','pcs',15.0,120),
('manopera',122,'Instalare ODF','pcs',15.0,121),
('manopera',123,'Instalare Wallbox','buc',15.0,122),
('manopera',124,'CPE uninstall and recovery from the client','buc',20.0,123),
('manopera',125,'Reconfiguration of an existing CPE','buc',25.0,124),
('manopera',126,'Uninstall Media Convertor','buc',5.0,125),
('manopera',127,'Uninstall Wallbox','buc',5.0,126),
('manopera',128,'Uninstall ODF','buc',10.0,127),
('manopera',129,'Uninstall cabinet or rack, tipic 10 RU in  client location','buc',34.0,128),
('manopera',130,'Equipping odf with signal (in POP)','buc',15.0,129),
('manopera',131,'Additional ports in POP equipment','buc',31.25,130),
('manopera',132,'Instalare FO Messenger 2 fire pe stalpi','km',380.0,131),
('manopera',133,'Realizare circuit distributie CATV/D4A','luc',30.0,132),
('manopera',134,'Realizare circuit distributie CATV/D4A + CPE (Data/VOIP)','luc',37.0,133),
('manopera',135,'Instalare CPE','luc',25.0,134),
('manopera',136,'Extindere circuit de distributie','buc',25.0,135),
('manopera',137,'Migrare retea aeriana prin subsol bloc',NULL,15.0,136),
('manopera',138,'Pregatire ordin de lucru B2B','buc',20.0,137),
('manopera',139,'Configurare echipament CPE pus la dispozitie de Beneficiar','buc',25.0,138),
('manopera',140,'Installation accessories for FO ADSS FO cable "Barcuta"','buc',0.5281,139),
('manopera',141,'Installation accessories for FO ADSS FO cable "Colier tabla inox"','buc',0.3873,140),
('manopera',142,'Installation accessories for FO ADSS FO cable "Carlig"','buc',0.3142,141),
('manopera',143,'Installation accessories for FO ADSS FO cable "Armorod"','buc',5.6875,142),
('manopera',144,'Warning binder','m',0.3,143),
('manopera',145,'Large equipment transportation','km',1.0,144),
('manopera',146,'FO design service','pcs',35.0,145),
('manopera',147,'FO acceptance verification service','pcs',35.0,146),
('manopera',148,'Re-verification of rejected FO acceptance (by Vodafone) service','pcs',35.0,147),
('manopera',149,'Lucrari atipice (om lucru/ora)','hour',17.0,148),
('manopera',150,'Taxa urgenta incident  P1','lucr',81.25,149),
('manopera',151,'Taxa urgenta incident  P2','lucr',67.7083,150),
('manopera',152,'Taxa urgenta incident  P3','lucr',54.17,151),
('manopera',153,'Taxa urgenta incident  P4','lucr',40.625,152),
('manopera',154,'Obtinere acord de instalare de la proprietari sau asociatia de proprietari','luc',15.0,153),
('manopera',155,'Obtinere Certificat de Urbanism','buc',119.0,154),
('manopera',156,'Obtinere avize de la proprietarii de infrastructura','buc',55.0,155),
('manopera',157,'Obtinere avize cerute prin Certificatul de Urbanism','buc',65.0,156),
('manopera',158,'Obtinere AC','buc',127.5,157),
('manopera',159,'Diligente ISC(anunt deschidere lucrari, anunt finalizare lucrari, incheie proces verbal de receptie)','buc',20.0,158),
('manopera',160,'Dirigentie de santier','buc',20.0,159),
('manopera',161,'Responsabil tehnic cu executia lucrarilor (RTE)','buc',20.0,160),
('manopera',162,'Ridicare topografica','km',297.5,161),
('manopera',163,'Proiectare traseu subteran','km',255.0,162),
('manopera',164,'Proiect subtraversare CFR, drumuri, rauri','pcs',0,163),
('manopera',165,'Proiect DDE, traseu aerian pe LEA  JT si MT','km',0,164),
('manopera',166,'Proiect DDE, traseu aerian pe LEA 110 kV','km',0,165),
('manopera',167,'Studiu de coexistenta','Stalp',7.0,166),
('materiale',1,'Accesorii montare pentru cablu fibra optica ADSS','Km',90.74,167),
('materiale',2,'Accesoriu de instalare cablu FO ADSS "Barcuta"','pcs',0.53,168),
('materiale',3,'Accesoriu de instalare cablu FO ADSS "Colier tabla inox"','pcs',0.39,169),
('materiale',4,'Accesoriu de instalare cablu FO ADSS "Carlig"','pcs',0.31,170),
('materiale',5,'Accesoriu de instalare cablu FO ADSS  "Armorod"','pcs',5.69,171),
('materiale',6,'Furnizare cutie de jonctiune pentru cablu FO ADSS, 12 jonctiuni, plastic','pcs',63.0,172),
('materiale',7,'Furnizare cutie de jonctiune pentru cablu FO ADSS, pana la 96 jonctiuni, plastic','pcs',63.0,173),
('materiale',8,'Furnizare cutie de jonctiune pentru ADSS, pana la 192 jonctiuni, plastic','pcs',81.9,174),
('materiale',9,'Furnizare cutie de jonctiune pentru OPGW, metalica','pcs',224.7,175),
('materiale',10,'Furnizare cutie de jonctiune paralelipipedica pt instalare la exterior pe perete/bransamente (max. 6 intrari)','pcs',80.5,176),
('materiale',11,'Monotub HDPE 40 mm','m',0.7,177),
('materiale',12,'Monotub HDPE 63 mm','m',1.26,178),
('materiale',13,'Tubeta 8/10mm','m',1.61,179),
('materiale',14,'Tubeta 10/14mm','m',1.75,180),
('materiale',15,'Pat cablu plastic 2-6 mm','m',1.4,181),
('materiale',16,'Pat cablu plastic 8-12 mm','m',1.75,182),
('materiale',17,'Folie avertizoare','m',0.35,183),
('materiale',18,'Markeri electronici','pcs',10.5,184),
('materiale',19,'Teava PVC tip G  M110 / Ø 120','m',7.0,185),
('materiale',20,'Teava OL Ø 60','m',3.941,186),
('materiale',21,'Copex din plastic Ø 32','m',2.1,187),
('materiale',22,'Copex metallic  32','m',1.75,188),
('materiale',23,'Aparatoare U75 montata pe zid aparent','pcs',17.5,189),
('materiale',24,'Banda semnalizare','km',93.8,190),
('materiale',25,'Furnizare stalp LEA (12m)','pcs',415.1,191),
('materiale',26,'Furnizare stalp material compozit, amplasare in linie','pcs',0.0,192),
('materiale',27,'Furnizare stalp material compozit, sustinere/rezistenta','pcs',0.0,193),
('materiale',28,'Furnizare stalp metalic','pcs',126.0,194),
('materiale',29,'Furnizare stalp de lemn impregnat','pcs',91.0,195);